# Generated by Django 5.2 on 2025-04-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shangrila_backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration", models.PositiveIntegerField(help_text="Duration in days")),
                ("destination", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="package_images/")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
